# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  gamestateservice:
    image: gamestateservice
    build:
      context: .
      dockerfile: GameStateService/Dockerfile
    ports:
      - 5000:5000
