name: Deploy GameState Service to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore ./game-state-service/GameStateService/GameStateService.csproj

    - name: Build the project
      run: dotnet build ./game-state-service/GameStateService/GameStateService.csproj --configuration Release --no-restore

    - name: Publish the project
      run: dotnet publish ./game-state-service/GameStateService/GameStateService.csproj -c Release -o ./publish

    - name: Build Docker image
      run: |
        docker build -t dlee930cs397registry.azurecr.io/gamestateservice:latest \
          -f ./game-state-service/GameStateService/Dockerfile ./game-state-service

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: dlee930cs397registry.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push Docker image to ACR
      run: docker push dlee930cs397registry.azurecr.io/gamestateservice:latest
